# Generated by Django 3.0 on 2020-09-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0003_auto_20200910_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='abdul kalam.jpg', upload_to='profile_image'),
        ),
    ]
