# Generated by Django 3.0 on 2020-09-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0005_auto_20200911_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, default='this is your status', max_length=200),
        ),
    ]
