# Generated by Django 3.0 on 2020-09-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0012_auto_20200912_2132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
