# Generated by Django 3.0 on 2020-09-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0013_auto_20200912_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='abdul kalam.jpg', upload_to='profile_image'),
        ),
    ]
